# Generated by Django 5.2.3 on 2025-06-17 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non-binary')], max_length=1)),
                ('body_type', models.CharField(choices=[('slim', 'Slim'), ('athletic', 'Athletic'), ('muscular', 'Muscular'), ('curvy', 'Curvy'), ('plus_size', 'Plus Size')], max_length=20)),
                ('vrm_file_url', models.URLField()),
                ('preview_image_url', models.URLField(blank=True)),
                ('skin_tones', models.JSONField(default=list, help_text='Available skin tone hex codes')),
                ('hair_colors', models.JSONField(default=list, help_text='Available hair color hex codes')),
                ('outfit_options', models.JSONField(default=list, help_text='Available outfit configurations')),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'avatars',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AvatarPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('skin_tone', models.CharField(max_length=7)),
                ('hair_color', models.CharField(max_length=7)),
                ('outfit_config', models.JSONField()),
                ('is_featured', models.BooleanField(default=False)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avatars.avatar')),
            ],
            options={
                'db_table': 'avatar_presets',
                'ordering': ['-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('skin_tone', models.CharField(blank=True, help_text='Hex color code', max_length=7)),
                ('hair_color', models.CharField(blank=True, help_text='Hex color code', max_length=7)),
                ('outfit_config', models.JSONField(default=dict, help_text='Selected outfit configuration')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('motivation_message', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_interacted', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avatars.avatar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_avatars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_avatars',
                'ordering': ['day_of_week'],
                'unique_together': {('user', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='AvatarInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('workout_start', 'Workout Started'), ('workout_complete', 'Workout Completed'), ('goal_achieved', 'Goal Achieved'), ('streak_milestone', 'Streak Milestone'), ('custom_message', 'Custom Message'), ('encouragement', 'Encouragement')], max_length=30)),
                ('message', models.TextField()),
                ('animation_trigger', models.CharField(blank=True, max_length=50)),
                ('context_data', models.JSONField(default=dict, help_text='Additional data for the interaction')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='avatars.useravatar')),
            ],
            options={
                'db_table': 'avatar_interactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
